sudo: false
language:
- node_js
node_js:
- "6"
script:
- npm run lint
- npm run cs-check
- npm run test-api:start
- npm run test
- npm run test-api:stop
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
